version: "3.8"

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:8.0.20
    restart: always
    environment:
      MYSQL_DATABASE: fmcdata
      MYSQL_PASSWORD: Mevsept123
      MYSQL_ROOT_PASSWORD: Mevsept123
    ports:
      - "3307:3306"
    networks:
      - fmc-mysql
    volumes:
      - db:/var/lib/mysql

  accountservice:
    depends_on:
      - mysqldb
    networks:
      - fmc-mysql
    build: ./accountservice
    ports:
      - "8082:8082"
    volumes:
      - .m2:/root/.m2

  userservice:
    depends_on:
      - mysqldb
    networks:
      - fmc-mysql
    build: ./userservice
    ports:
      - "8083:8083"
    volumes:
      - .m2:/root/.m2
volumes:
  db:

networks:
  fmc-mysql: